# Generated by Django 6.0 on 2025-12-25 05:00

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='ProhibitedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('name_normalized', models.CharField(db_index=True, help_text='Lowercase, trimmed version', max_length=500)),
                ('cas_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ec_number', models.CharField(blank=True, max_length=50, null=True)),
                ('regulation', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cmr', models.BooleanField(default=False, help_text='Carcinogenic, Mutagenic, or Toxic for Reproduction')),
                ('cmr_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prohibited_ingredients',
                'indexes': [models.Index(fields=['name'], name='prohibited__name_52a39e_idx'), models.Index(fields=['name_normalized'], name='prohibited__name_no_051679_idx'), models.Index(fields=['cas_number'], name='prohibited__cas_num_1e62a4_idx'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_gin_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
