# Generated by Django 6.0 on 2025-12-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='cas_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='ec_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
