# Generated by Django 6.0 on 2025-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_prohibitedingredient_cas_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='name_normalized',
            field=models.TextField(db_index=True, help_text='Lowercase, trimmed version'),
        ),
    ]
