# Generated by Django 6.0 on 2025-12-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_prohibitedingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='cas_number',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='ec_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='regulation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
