# Generated by Django 6.0 on 2025-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_prohibitedingredient_cas_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('input_source', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20)),
                ('result_json', models.JSONField()),
                ('overall_status', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('prohibited', 'Prohibited')], default='safe', max_length=20)),
                ('total_ingredients', models.PositiveIntegerField(default=0)),
                ('prohibited_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('safe_count', models.PositiveIntegerField(default=0)),
                ('analysis_duration_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='cas_number',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='ec_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prohibitedingredient',
            name='regulation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
